name: kuran_meali
description: A new Flutter project.
publish_to: "none"
version: 2.0.1+4

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  launch_review: ^3.0.1
  pdfx: ^2.3.0
  share_plus: ^7.1.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
