name: kuran_meali
description: A new Flutter project.
publish_to: "none"
version: 3.0.0+5

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  get_storage: ^2.1.1
  launch_review: ^3.0.1
  share_plus: ^7.1.0
  url_launcher: ^6.1.10
  syncfusion_flutter_pdfviewer: ^23.2.7
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/docs/
    - assets/icons/

changelog: |
  # Change Log - Version 3.0.0+5

  New Feature:
  - Added copy text feature.

  Library Updates:
  - Changed PDF viewer library for enhanced functionality.

  New Library Added:
  - Added `provider` library for enhanced state management.

  File Organization:
  - Splitted the PDF file into 114 parts for better performance.

  UI Enhancements:
  - Made small changes to the user interface for a better user experience.