name: kuran_meali
description: A new Flutter project.
publish_to: "none"
version: 3.1.0+6

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  get_storage: ^2.1.1
  launch_review: ^3.0.1
  share_plus: ^7.1.0
  url_launcher: ^6.1.10
  syncfusion_flutter_pdfviewer: ^23.2.7
  provider: ^6.1.1
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/docs/
    - assets/icons/

changelog: |
  # Change Log - Version 3.1.0+6

  Project Structure:
  - Updated folder structure for better organization.

  Issue Fix:
  - Distortions in the copied text is a little fixed.

  UI Enhancements:
  - Surahs dialog replaced with a bottom sheet for improved user experience.

  New Library Added:
  - Added `top_snackbar_flutter` library for enhanced snackbar functionality.

  User Experience:
  - Enhanced the skip-to-next-surah button, allowing it to jump 5 pages forward for improved functionality.

